dist: focal

cache:
  directories:
  - $HOME/.m2

addons:
  chrome: stable
  sonarcloud:
    organization: "bordertech-github"
    token: $SONAR_TOKEN

before_install:
- echo "MAVEN_OPTS='-Xmx512m -XX:MaxPermSize=128m'" > ~/.mavenrc
- mvn clean
## Chromedriver setup
- wget -N http://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

language: Java
jdk:
 - openjdk11

## Travis installs the project with the following maven command:- "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
script:
 - mvn package sonar:sonar -Dsonar.projectKey="bordertech-sample-app"
